export const cityList = [
  {
    "options":[
      {
        "text":"北京市",
        "value":"110000"
      },
      {
        "text":"澳门特别行政区",
        "value":"820000"
      }
    ]
  },
  {
    "options":[
      {
        "text":"市辖区",
        "value":"810100",
        "parentVal":"810000"
      },
      {
        "text":"自治区直辖县级行政区划",
        "value":"659000",
        "parentVal":"650000"
      }
    ]
  },
  {
    "options":[
      {
        "text":"东城区",
        "value":"110101",
        "parentVal":"110100"
      },
      {
        "text":"路氹城",
        "value":"820301",
        "parentVal":"820300"
      }
    ]
  }
]
